/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author carlos
 */
public class ABMProducto extends javax.swing.JInternalFrame {

    ControladoraVisual miVisual;
    DefaultComboBoxModel comboEstado = new DefaultComboBoxModel();
    /**
     * Creates new form ABMArticulo
     */
    public ABMProducto(ControladoraVisual miVisual) {
        this.miVisual=miVisual;        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCantidadMinimaMayorista = new javax.swing.JTextField();
        txtPrecioMayorista = new javax.swing.JTextField();
        txtPrecioMinorista = new javax.swing.JTextField();
        txtCantidadDeEjemplares = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-delete-file-32.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-edit-file-32.png"))); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-add-32.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-search-32.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(23, 23, 23)
                .addComponent(btnModificar)
                .addGap(23, 23, 23)
                .addComponent(btnBorrar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setText("Código de Barra");

        jLabel2.setText("Nombre articulo");

        jLabel3.setText("Precio");

        jLabel4.setText("Precio Proveedor");

        jLabel5.setText("Porcentaje de Recarga");

        jLabel7.setText("Cantidad de Unidades");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtCantidadDeEjemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadDeEjemplaresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadMinimaMayorista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecioMayorista)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadDeEjemplares, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecioMinorista))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidadMinimaMayorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtPrecioMayorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecioMinorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidadDeEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        /*String idArticulo, nombreArticulo;
        int cantidadMinimaMayorista;
        double precioMayorista, precioMinorista;
        
        idArticulo = txtId.getText();
        nombreArticulo = txtNombre.getText();
        cantidadMinimaMayorista = Integer.parseInt(txtCantidadMinimaMayorista.getText());
        precioMayorista = Double.parseDouble(txtPrecioMayorista.getText());
        precioMinorista = Double.parseDouble(txtPrecioMinorista.getText());
        
        try {
            this.miVisual.altaArticulo(idArticulo, nombreArticulo, cantidadMinimaMayorista, precioMayorista, precioMinorista);
            this.miVisual.buscarArticulo(idArticulo).altaEjemplarNum(Integer.parseInt(txtCantidadDeEjemplares.getText()));
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(ABMProducto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExceptionBusqueda ex) {
            JOptionPane.showMessageDialog(null, "El articulo ya existe.");
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(ABMProducto.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        /*String id, nombre;
        int cantidadMinimaMayorista;
        double precioMayorista, precioMinorista;
        try {
            id = txtId.getText();
            nombre = this.miVisual.buscarArticulo(id).getNombreArticulo();
            cantidadMinimaMayorista = this.miVisual.buscarArticulo(id).getCantidadMinimaMayorista();
            precioMayorista = this.miVisual.buscarArticulo(id).getPrecioMayorista();
            precioMinorista = this.miVisual.buscarArticulo(id).getPrecioMinorista();
            
            txtNombre.setText(nombre);
            txtCantidadMinimaMayorista.setText(String.valueOf(cantidadMinimaMayorista));
            txtPrecioMayorista.setText(String.valueOf(precioMayorista));
            txtPrecioMinorista.setText(String.valueOf(precioMinorista));
            txtCantidadDeEjemplares.setText(String.valueOf(this.miVisual.buscarArticulo(id).stockEjemplaresCantidad()));
            
        } catch (ExceptionBusqueda ex) {
            JOptionPane.showMessageDialog(null, "No Existe el articulo.");
        }*/
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        /*int cantidad = Integer.parseInt(txtCantidadMinimaMayorista.getText());
        double precioMayorista, precioMinorista;
        precioMayorista = Double.parseDouble(txtPrecioMayorista.getText());
        precioMinorista = Double.parseDouble(txtPrecioMinorista.getText());
        
        try {
            this.miVisual.modificarArticulo(txtId.getText(), txtNombre.getText(), cantidad, precioMayorista, precioMinorista);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(ABMProducto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExceptionBusqueda ex) {
            
        }*/
        
    }//GEN-LAST:event_btnModificarActionPerformed

    
    
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        /*try {
            this.miVisual.borrarArticulo(txtId.getText());
        } catch (ExceptionBusqueda ex) {
            JOptionPane.showMessageDialog(null, "No existe el Articulo.");
        }*/
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtCantidadDeEjemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadDeEjemplaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadDeEjemplaresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtCantidadDeEjemplares;
    private javax.swing.JTextField txtCantidadMinimaMayorista;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioMayorista;
    private javax.swing.JTextField txtPrecioMinorista;
    // End of variables declaration//GEN-END:variables

  
}
//ValidacionDeCampos unaValidacion = new ValidacionDeCampos();
//    ControladoraVisual miVisual;
//    DefaultComboBoxModel comboIVA = new DefaultComboBoxModel();
//
//    /**
//     * Creates new form AltaClientee
//     */
//    public ABMCliente(ControladoraVisual miVisual) {
//        this.miVisual = miVisual;
//        initComponents();
//        cargarCombo();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        txtDniCliente = new javax.swing.JTextField();
//        txtNombreCliente = new javax.swing.JTextField();
//        txtDireccionCliente = new javax.swing.JTextField();
//        btnAnadir = new javax.swing.JButton();
//        cmbTipoIVA = new javax.swing.JComboBox<>();
//        jLabel4 = new javax.swing.JLabel();
//        btnBorrar = new javax.swing.JButton();
//        btnModificar = new javax.swing.JButton();
//        btnBuscar = new javax.swing.JButton();
//        jLabel6 = new javax.swing.JLabel();
//        cmbEstado = new javax.swing.JComboBox<>();
//
//        setClosable(true);
//        setIconifiable(true);
//        setMaximizable(true);
//        setResizable(true);
//        setTitle("ABMCliente");
//        setToolTipText("");
//
//        jLabel1.setText("Dni:");
//
//        jLabel2.setText("Nombre:");
//
//        jLabel3.setText("Direccion:");
//
//        btnAnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
//        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnAnadirActionPerformed(evt);
//            }
//        });
//
//        cmbTipoIVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
//
//        jLabel4.setText("TipoIVA:");
//
//        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/block.png"))); // NOI18N
//        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnBorrarActionPerformed(evt);
//            }
//        });
//
//        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alt-editar-icono-5470-64.png"))); // NOI18N
//        btnModificar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnModificarActionPerformed(evt);
//            }
//        });
//
//        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
//        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnBuscarActionPerformed(evt);
//            }
//        });
//
//        jLabel6.setText("Estado:");
//
//        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jLabel1)
//                            .addComponent(jLabel2)
//                            .addComponent(jLabel3)
//                            .addComponent(jLabel4))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                            .addComponent(cmbTipoIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(txtDniCliente)
//                            .addComponent(txtNombreCliente)
//                            .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGap(38, 38, 38))
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(18, 18, 18)
//                        .addComponent(btnAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(jLabel6)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(168, 168, 168))))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(19, 19, 19)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .addComponent(btnAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(jLabel1)
//                        .addGap(18, 18, 18)
//                        .addComponent(jLabel2))
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(18, 18, 18)
//                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                .addGap(18, 18, 18)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel3)
//                    .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(cmbTipoIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel4))
//                .addGap(18, 18, 18)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel6)
//                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addContainerGap(15, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>                        
//
//    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
//        String nombreORazon, direccion, dni;
//        dni = txtDniCliente.getText();
//        nombreORazon = txtNombreCliente.getText();
//        direccion = txtDireccionCliente.getText();
//        List<String> datosValidos = new LinkedList();
//        datosValidos.add(dni);
//        datosValidos.add(nombreORazon);
//        datosValidos.add(direccion);
//        if (!this.unaValidacion.validar(datosValidos)) {
//            try {
//                this.miVisual.altaCliente(dni, nombreORazon, direccion, this.miVisual.buscarTipoIVA(String.valueOf(cmbTipoIVA.getSelectedItem())));
//                //System.out.println(String.valueOf(cmbTipoIVA.getSelectedItem()));
//            } catch (PreexistingEntityException ex) {
//                Logger.getLogger(ABMCliente.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
//
//    }                                         
//
//    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        Cliente unCliente;
//        String nombreORazon, direccion, dni;
//        dni = txtDniCliente.getText();
//        //System.out.println(dni);
////        this.miVisual.buscarCliente(dni);
////        unCliente=this.miVisual.buscarCliente(dni);
//        try {
//            nombreORazon = this.miVisual.buscarCliente(dni).getNombreORazon();
//            direccion = this.miVisual.buscarCliente(dni).getDireccion();
//            //this.comboIVA.addElement(this.miVisual.buscarCliente(dni).buscarTipoIvaDeCliente().getDescripcion());
//            cmbTipoIVA.setSelectedIndex(Integer.parseInt(this.miVisual.buscarCliente(dni).buscarTipoIvaDeCliente().getCodigo()) - 1);
//            //cmbTipoIVA.setModel(comboIVA);
//            txtDniCliente.setText(String.valueOf(dni));
////        System.out.println(nombreORazon);
//            txtNombreCliente.setText(nombreORazon);
//            txtDireccionCliente.setText(direccion);
//        } catch (ExceptionBusquedaCliente ex) {
//            JOptionPane.showMessageDialog(null, ex.getMensaje());
//        }
//
//    }                                         
//
//    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        try {
//            this.miVisual.borrarCliente(txtDniCliente.getText());
//        } catch (ExceptionBusquedaCliente ex) {
//            Logger.getLogger(ABMCliente.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }                                         
//
//    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {                                             
//        try {
//            this.miVisual.modificarCliente(txtDniCliente.getText(), txtNombreCliente.getText(),
//                    txtDireccionCliente.getText(),
//                    this.miVisual.buscarTipoIVA(String.valueOf(cmbTipoIVA.getSelectedItem())));
//        } catch (ExceptionBusquedaCliente ex) {
//            Logger.getLogger(ABMCliente.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (NonexistentEntityException ex) {
//            Logger.getLogger(ABMCliente.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }                                            
//
//    private void cargarCombo() {
//        List<TipoIVA> auxLista = this.miVisual.dameTodosLosTiposIVAs();
//        //for each por cada: objeto de la listacoleccion hacer
//        for (TipoIVA aux : auxLista) {
//            this.comboIVA.addElement(aux.getDescripcion());
//            //System.out.println(aux.getDescripcion());
//        }
//        //System.out.println(auxLista.size());
//        //this.comboIVA.addElement("Hola");
//        //this.comboIVA.addElement("anda");
//        cmbTipoIVA.setModel(comboIVA);
//    }
