/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Logica.Producto;
import Persistencia.exceptions.NonexistentEntityException;
import Persistencia.exceptions.PreexistingEntityException;
import java.awt.Color;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabrieldehner
 */
public class MenuPrincipal extends javax.swing.JFrame {

    ControladoraVisual controladoraVisual = new ControladoraVisual();
    static boolean maximized = true;
    int xMouse;
    int yMouse;

    String path = "";
    Double porcentajeRecarga = -1.0;

    /**
     * Creates new form ControladoraVisual
     */
    public MenuPrincipal() {
        /* try {
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
         } catch (Exception e) {
         e.printStackTrace();
         }*/
        try {

            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        //this.setIconImage(new ImageIcon(getClass().getResource("./../Imagenes/idea.png")).getImage());
        initComponents();
        
        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(pnlHome);

        /*
        
         Actualizar actualizar = new Actualizar(controladoraVisual);
         this.panelWork.add(actualizar);
         actualizar.show();
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnMaximize = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnPru1 = new javax.swing.JButton();
        btnPru2 = new javax.swing.JButton();
        lblHome = new javax.swing.JLabel();
        lblPru1 = new javax.swing.JLabel();
        lblPru2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlBody = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlActualizar = new javax.swing.JPanel();
        lblRuta = new javax.swing.JLabel();
        inputRecarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnExplorar = new javax.swing.JButton();
        pnlBuscar = new javax.swing.JPanel();
        txtInputText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductosScreen = new javax.swing.JTable();
        jRadioCodBarras = new javax.swing.JRadioButton();
        jRadioCodProv = new javax.swing.JRadioButton();
        jRadioNombre = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Librería Ingenio");
        setBackground(new java.awt.Color(196, 208, 190));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 600));

        pnlHeader.setBackground(new java.awt.Color(2, 117, 216));
        pnlHeader.setForeground(new java.awt.Color(2, 117, 216));
        pnlHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlHeaderMouseDragged(evt);
            }
        });
        pnlHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHeaderMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(2, 117, 216));
        btnExit.setForeground(new java.awt.Color(2, 117, 216));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setContentAreaFilled(false);
        btnExit.setMaximumSize(new java.awt.Dimension(30, 30));
        btnExit.setMinimumSize(new java.awt.Dimension(30, 30));
        btnExit.setOpaque(true);
        btnExit.setPreferredSize(new java.awt.Dimension(30, 30));
        btnExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit (2).png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnMaximize.setBackground(new java.awt.Color(2, 117, 216));
        btnMaximize.setForeground(new java.awt.Color(2, 117, 216));
        btnMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Maximize.png"))); // NOI18N
        btnMaximize.setBorder(null);
        btnMaximize.setContentAreaFilled(false);
        btnMaximize.setOpaque(true);
        btnMaximize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Maximize (2).png"))); // NOI18N
        btnMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseEntered(evt);
            }
        });
        btnMaximize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximizeActionPerformed(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(2, 117, 216));
        btnMinimize.setForeground(new java.awt.Color(2, 117, 216));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimize.png"))); // NOI18N
        btnMinimize.setBorder(null);
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setOpaque(true);
        btnMinimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimize (2).png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
        });
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-bookmark-book-64.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Phetsarath OT", 1, 24)); // NOI18N
        jLabel5.setText("Librería Ingenio");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMaximize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(2, 117, 216));
        jPanel1.setForeground(new java.awt.Color(2, 117, 216));

        btnHome.setBackground(new java.awt.Color(2, 117, 216));
        btnHome.setFont(new java.awt.Font("Jamrul", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("HOME");
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setMaximumSize(new java.awt.Dimension(120, 40));
        btnHome.setMinimumSize(new java.awt.Dimension(120, 40));
        btnHome.setPreferredSize(new java.awt.Dimension(120, 40));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnPru1.setBackground(new java.awt.Color(2, 117, 216));
        btnPru1.setFont(new java.awt.Font("Jamrul", 1, 14)); // NOI18N
        btnPru1.setForeground(new java.awt.Color(255, 255, 255));
        btnPru1.setText("ACTUALIZAR");
        btnPru1.setBorder(null);
        btnPru1.setBorderPainted(false);
        btnPru1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPru1.setMaximumSize(new java.awt.Dimension(120, 40));
        btnPru1.setMinimumSize(new java.awt.Dimension(120, 40));
        btnPru1.setPreferredSize(new java.awt.Dimension(120, 40));
        btnPru1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPru1ActionPerformed(evt);
            }
        });

        btnPru2.setBackground(new java.awt.Color(2, 117, 216));
        btnPru2.setFont(new java.awt.Font("Jamrul", 1, 14)); // NOI18N
        btnPru2.setForeground(new java.awt.Color(255, 255, 255));
        btnPru2.setText("BUSCAR");
        btnPru2.setBorder(null);
        btnPru2.setBorderPainted(false);
        btnPru2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPru2.setMaximumSize(new java.awt.Dimension(120, 40));
        btnPru2.setMinimumSize(new java.awt.Dimension(120, 40));
        btnPru2.setPreferredSize(new java.awt.Dimension(120, 40));
        btnPru2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPru2ActionPerformed(evt);
            }
        });

        lblHome.setBackground(new java.awt.Color(74, 172, 125));
        lblHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblHome.setOpaque(true);

        lblPru1.setBackground(new java.awt.Color(2, 117, 216));
        lblPru1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblPru1.setOpaque(true);

        lblPru2.setBackground(new java.awt.Color(2, 117, 216));
        lblPru2.setForeground(new java.awt.Color(2, 117, 216));
        lblPru2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblPru2.setOpaque(true);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPru1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(lblPru1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPru2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPru2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPru1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPru2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                    .addComponent(lblPru1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPru2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pnlBody.setBackground(new java.awt.Color(196, 208, 190));
        pnlBody.setForeground(new java.awt.Color(196, 208, 190));
        pnlBody.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(196, 208, 190));
        pnlHome.setForeground(new java.awt.Color(196, 208, 190));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel6)
                .addContainerGap(935, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        pnlBody.add(pnlHome, "card4");

        pnlActualizar.setBackground(new java.awt.Color(196, 208, 190));
        pnlActualizar.setForeground(new java.awt.Color(196, 208, 190));

        lblRuta.setText("Ruta: ");

        inputRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRecargaActionPerformed(evt);
            }
        });

        jLabel7.setText("Ingrese el porcentaje de recargo");

        btnConfirmar.setBackground(new java.awt.Color(196, 208, 190));
        btnConfirmar.setForeground(new java.awt.Color(196, 208, 190));
        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-next-48.png"))); // NOI18N
        btnConfirmar.setBorder(null);
        btnConfirmar.setBorderPainted(false);
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseEntered(evt);
            }
        });
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnExplorar.setBackground(new java.awt.Color(196, 208, 190));
        btnExplorar.setForeground(new java.awt.Color(196, 208, 190));
        btnExplorar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-microsoft-excel-48.png"))); // NOI18N
        btnExplorar.setBorder(null);
        btnExplorar.setBorderPainted(false);
        btnExplorar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExplorarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExplorarMouseEntered(evt);
            }
        });
        btnExplorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExplorarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlActualizarLayout = new javax.swing.GroupLayout(pnlActualizar);
        pnlActualizar.setLayout(pnlActualizarLayout);
        pnlActualizarLayout.setHorizontalGroup(
            pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlActualizarLayout.createSequentialGroup()
                        .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExplorar)
                            .addGroup(pnlActualizarLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(220, 698, Short.MAX_VALUE))))
        );
        pnlActualizarLayout.setVerticalGroup(
            pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarLayout.createSequentialGroup()
                .addComponent(btnExplorar)
                .addGap(14, 14, 14)
                .addComponent(lblRuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlActualizarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pnlBody.add(pnlActualizar, "card3");

        pnlBuscar.setBackground(new java.awt.Color(196, 208, 190));
        pnlBuscar.setForeground(new java.awt.Color(196, 208, 190));
        pnlBuscar.setPreferredSize(new java.awt.Dimension(914, 450));

        jLabel4.setText("Buscar Artículo por");

        btnConfirm.setBackground(new java.awt.Color(196, 208, 190));
        btnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-search-32.png"))); // NOI18N
        btnConfirm.setBorder(null);
        btnConfirm.setBorderPainted(false);
        btnConfirm.setMaximumSize(new java.awt.Dimension(45, 45));
        btnConfirm.setMinimumSize(new java.awt.Dimension(45, 45));
        btnConfirm.setPreferredSize(new java.awt.Dimension(45, 45));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        tableProductosScreen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tableProductosScreen);

        jRadioCodBarras.setBackground(new java.awt.Color(196, 208, 190));
        jRadioCodBarras.setText("Código de Barras");
        jRadioCodBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCodBarrasActionPerformed(evt);
            }
        });

        jRadioCodProv.setBackground(new java.awt.Color(196, 208, 190));
        jRadioCodProv.setText("Código Proveedor");
        jRadioCodProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCodProvActionPerformed(evt);
            }
        });

        jRadioNombre.setBackground(new java.awt.Color(196, 208, 190));
        jRadioNombre.setText("Nombre");
        jRadioNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarLayout = new javax.swing.GroupLayout(pnlBuscar);
        pnlBuscar.setLayout(pnlBuscarLayout);
        pnlBuscarLayout.setHorizontalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioCodProv)
                            .addComponent(jRadioCodBarras)
                            .addComponent(jRadioNombre)))
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBuscarLayout.setVerticalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jRadioCodBarras)
                .addGap(0, 0, 0)
                .addComponent(jRadioCodProv)
                .addGap(0, 0, 0)
                .addComponent(jRadioNombre)
                .addGap(1, 1, 1)
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBody.add(pnlBuscar, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 137, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1018, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new Color(2, 117, 216));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnMaximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseEntered
        btnMaximize.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_btnMaximizeMouseEntered

    private void btnMaximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseExited
        btnMaximize.setBackground(new Color(2, 117, 216));
    }//GEN-LAST:event_btnMaximizeMouseExited

    private void btnMaximizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximizeActionPerformed
        if (maximized) {
            //handle fullscreen - taskbar
            MenuPrincipal.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            MenuPrincipal.this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximized = false;
        } else {
            setExtendedState(JFrame.NORMAL);
            maximized = true;
        }
    }//GEN-LAST:event_btnMaximizeActionPerformed

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setBackground(new Color(2, 117, 216));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void pnlHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlHeaderMousePressed

    private void pnlHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMouseDragged
        if (maximized) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x - xMouse, y - yMouse);
        }
    }//GEN-LAST:event_pnlHeaderMouseDragged

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        lblHome.setBackground(new Color(74, 172, 125));

        lblPru1.setBackground(new Color(2, 117, 216));
        lblPru2.setBackground(new Color(2, 117, 216));

        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(pnlHome);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnPru1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPru1ActionPerformed
        lblPru1.setBackground(new Color(74, 172, 125));

        lblHome.setBackground(new Color(2, 117, 216));
        lblPru2.setBackground(new Color(2, 117, 216));

        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(pnlActualizar);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_btnPru1ActionPerformed

    private void btnPru2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPru2ActionPerformed
        lblPru2.setBackground(new Color(74, 172, 125));

        lblPru1.setBackground(new Color(2, 117, 216));
        lblHome.setBackground(new Color(2, 117, 216));

        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(pnlBuscar);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_btnPru2ActionPerformed

    private void inputRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRecargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRecargaActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        if (!inputRecarga.getText().equals("")) {
            porcentajeRecarga = Double.parseDouble(inputRecarga.getText());
        }
        if (!path.equals("") && porcentajeRecarga != -1.0) {
            try {
                // TODO add your handling code here:
                this.controladoraVisual.actualizarProductos(path, porcentajeRecarga);
                JOptionPane.showMessageDialog(null, "Listo, los datos fueron actualizados!");
            } catch (PreexistingEntityException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un archivo válido e introduzca porcentaje de recarga");
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExplorarActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showDialog(btnExplorar, "Buscar Archivo");
        path = fc.getSelectedFile().toString();
        //JOptionPane.showInputDialog(null, path);

        lblRuta.setText("Ruta: " + path);

    }//GEN-LAST:event_btnExplorarActionPerformed

    private void btnExplorarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExplorarMouseEntered
        btnExplorar.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_btnExplorarMouseEntered

    private void btnExplorarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExplorarMouseExited
        btnExplorar.setBackground(new Color(196, 208, 190));
    }//GEN-LAST:event_btnExplorarMouseExited

    private void btnConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseEntered
        btnConfirmar.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_btnConfirmarMouseEntered

    private void btnConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseExited
        btnConfirmar.setBackground(new Color(196, 208, 190));
    }//GEN-LAST:event_btnConfirmarMouseExited

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        LinkedList<Producto> listaProductos = new LinkedList();
        if (jRadioCodProv.isSelected()) {
            Producto miProducto = this.controladoraVisual.buscarProducto(txtInputText.getText());
            if(miProducto!=null){
                listaProductos.add(miProducto);
            }
        }

        if (jRadioCodBarras.isSelected()) {
            Producto miProducto = this.controladoraVisual.buscarProductoIdScanner(txtInputText.getText());
             if(miProducto!=null){
                listaProductos.add(miProducto);
            }
        }

        if (jRadioNombre.isSelected()) {
            listaProductos = this.controladoraVisual.buscarProductoNombre(txtInputText.getText());
        }

        if (!listaProductos.isEmpty()) {
            String[] cabecera = {"Código", "Scanner", "Descripción", "Precio", "Porcentaje", "Precio Proveedor"};
            Object[][] datos = {};
            DefaultTableModel tablaProductos = new DefaultTableModel(datos, cabecera);
            tablaProductos = new DefaultTableModel(datos, cabecera);

            Iterator<Producto> iteradorProducto = listaProductos.iterator();
            Producto unProducto;
            while (iteradorProducto.hasNext()) {
                unProducto = iteradorProducto.next();
                Object[] vector = {unProducto.getCodigo(), unProducto.getScanner(), unProducto.getDescripcion(), unProducto.getPrecio(), unProducto.getPorcentaje(), unProducto.getPrecioProveedor() };
                tablaProductos.addRow(vector);
            }

            tableProductosScreen.setModel(tablaProductos);
        }else{
            JOptionPane.showMessageDialog(null, "No se encontraron productos!");
        }

    }//GEN-LAST:event_btnConfirmActionPerformed
    /*private void cargarTablaFiltrada(Articulo aux){
     String [] cabecera = {"Código", "Nombre", "Cant Vendida", "Cant Mínima", "Cant Actual"};
     Object [][] datos ={};
     tablaArticulos = new DefaultTableModel(datos, cabecera);
     Object [] vector = {aux.getIdArticulo(), aux, aux.stockEjemplaresVendidos(), aux.getCantidadMinimaMayorista(), aux.stockEjemplaresNoVendidos()};
     tablaArticulos.addRow(vector);
     tblArticulos.setModel(tablaArticulos);
     }*/

   // cargarTablaFiltrada(this.miVisual.buscarArticulo(txtCodigo.getText()));
    /*
     String [] cabecera = {"Código", "Nombre", "Cant Vendida", "Cant Mínima", "Cant Actual"};
     Object [] [] datos ={};
     tablaArticulos = new DefaultTableModel(datos, cabecera);
     cargarTablaArticulos(this.miVisual.dameTodosLosArticulosActivos());
     */
    private void jRadioCodBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCodBarrasActionPerformed
        jRadioCodProv.setSelected(false);
        jRadioNombre.setSelected(false);
    }//GEN-LAST:event_jRadioCodBarrasActionPerformed

    private void jRadioCodProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCodProvActionPerformed
        jRadioCodBarras.setSelected(false);
        jRadioNombre.setSelected(false);
    }//GEN-LAST:event_jRadioCodProvActionPerformed

    private void jRadioNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNombreActionPerformed
        jRadioCodBarras.setSelected(false);
        jRadioCodProv.setSelected(false);
    }//GEN-LAST:event_jRadioNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        
     java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     new ControladoraVisual().setVisible(true);
     }
     });
     }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExplorar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMaximize;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnPru1;
    private javax.swing.JButton btnPru2;
    private javax.swing.JTextField inputRecarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioCodBarras;
    private javax.swing.JRadioButton jRadioCodProv;
    private javax.swing.JRadioButton jRadioNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblPru1;
    private javax.swing.JLabel lblPru2;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JPanel pnlActualizar;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JTable tableProductosScreen;
    private javax.swing.JTextField txtInputText;
    // End of variables declaration//GEN-END:variables
}
